### ISSUE TITLE
[Feature Request] Effect while auto leveling with G29

### ISSUE THREAD

**Issue by hawkeyexp** [cp2004/OctoPrint-WS281x_LED_Status#102]
Hi,

it would be nice if you can implement a configurable effect during auto leveling (G29)

Thx

**Comment by cp2004** [comment]
I never replied to this, but had an idea - custom events, rather than me adding multiple specific ones (I have had a lot of requests for things like this) I would add user-configurable things, to react to gcode commands, @ commands or other events. It may come in the future, nothing specific yet.

**Comment by hawkeyexp** [comment]
Sounds nice :-)

**Comment by cp2004** [comment]
Closing in favour of #125, where custom triggers are being tracked. Early days but I intend to get this in the next release in a few months time.
