### ISSUE TITLE
[Request] Sacrificial pixel (led) support 

### ISSUE THREAD

**Issue by gladiatormax** [cp2004/OctoPrint-WS281x_LED_Status#109]
I use the first led for the 3.3v -> 5v data signal. Poor man's signal shifter.
See example here,

[https://hackaday.com/2017/01/20/cheating-at-5v-ws2812-control-to-use-a-3-3v-data-line/](https://hackaday.com/2017/01/20/cheating-at-5v-ws2812-control-to-use-a-3-3v-data-line/)

Could you add the option to ingnore first pixel(led) as also buing used in de wled project.

**Comment by cp2004** [comment]
I probably could, not for the next update (since that needs to be shipped at some point) but I will add it to the backlog.

**Comment by gladiatormax** [comment]
> I probably could, not for the next update (since that needs to be shipped at some point) but I will add it to the backlog.

Thx , for the rest great work on the plugin !

**Comment by cp2004** [comment]
This has been implemented ready for v0.8.0

**Comment by cp2004** [comment]
0.8.0 has been released (finally...!)
