### ISSUE TITLE
[Feature Request] Plugin reacting on Extruder / Filament changes (MMU)

### ISSUE THREAD

**Issue by Prutsium** [cp2004/OctoPrint-WS281x_LED_Status#120]
This is a feature request see video for purpose.

I would like to have the ability that the Plugin reacts on the current extruder used (1-5) in an MMU setup
So when Extruder 1 is used then leds 1-4 are on (with selected color), extruder 2 uses leds 5-8 (with selected color), and so on

This makes it possible to have selective light in MMU buffer setups.

Last but not least optional via Wled Api so the plugin sends the commands over the api to Wled :)

https://user-images.githubusercontent.com/42968695/110199958-74b3db80-7e5b-11eb-8dfc-feda58c590df.mp4

**Comment by Prutsium** [comment]
Seems the video doesnt show here so a link to the video on Youtube:
https://youtu.be/sUbybQ9KC38

**Comment by cp2004** [comment]
I'm unlikely to add such a specific configuration, as I said on Discord it will be more likely that there is a combination of segment control and custom events etc. to react to, and you can build this kind of setup yourself. I'm not sure how either of those are going to work or where they are going to turn up, it will be a while and they probably won't come at the same time.. While I would love to spend all day on this project it isn't going to happen unfortunately 😄.

**Comment by Prutsium** [comment]
Then we go for Plan B 😊
Mqtt into Nodered as i believe active extruder number is published by
Octoprint on mqtt.

**Comment by cp2004** [comment]
Closing in favour of #125, where options for custom triggers are being tracked. There were a few similar issues that are covered by this.
