### ISSUE TITLE
[Bug] bug report template has unclosed comment

### ISSUE THREAD

**Issue by kevinvalk** [cp2004/OctoPrint-WS281x_LED_Status#123]
**Description of the bug**
Whenever you create a new bug repport on Github the top comment is missing a closing tag.
`<!-- PLEASE don't delete any of the sections below, you will more than likely be asked for extra information if you do.`

**Comment by cp2004** [comment]
Thanks for pointing it out! It seems Github was smarter than me and coped anyway in most cases, but I guess easily broken like that. Added that closing comment in.
