### ISSUE TITLE
[Feature Request] more led strips

### ISSUE THREAD

**Issue by bustinex** [cp2004/OctoPrint-WS281x_LED_Status#127]
enable the management of more gpio pins so as to connect more led strips and concatenate them to make different effects.
for example: a led strip indicates the printing status; another and always white ...
or two contacted LED strips together mark the print progress.

**Comment by cp2004** [comment]
Hi @bustinex, the plugin currently supports the maximum number of different LED strips. When using SPI, as this plugin does you can only have one LED strip connected. You can of course join them together in a chain to make one longer strip.
