### ISSUE TITLE
[Feature Request] WLED Support

### ISSUE THREAD

**Issue by RootUser3885** [cp2004/OctoPrint-WS281x_LED_Status#129]
**Describe the feature you'd like:**

WLED support would make a nice feature

I would use it to change colors of led strips around the house when the print is done.

I saw a request for a similar feature as a duplicate and wanted to comment on the original but couldn't find it. (#10) I hate to add another duplicate.

**Why should this be implemented?**

WLED is growing in popularity and this would allow lights to be used across the network. Like changing cabinet lighting to chase green for a second after a print then return to what they were doing.

I could tie my PC lights to match my printer, or synchronize all the lights in the house.

This would also be good as another plugin entirely but it makes sense to be a feature here since they both use ws281x LEDs.

**Comment by cp2004** [comment]
Yes, this has been requested several times and I am almost done creating the WLED plugin. It's not going to be part of this plugin to make it easier to maintain - as soon as I add a WLED integration here people will be requesting WLED specific features and we will end up with two plugins in one.

https://github.com/cp2004/OctoPrint-WLED
