### ISSUE TITLE
[Feature Request] Control Tab 

### ISSUE THREAD

**Issue by ShadowOfTheDamn** [cp2004/OctoPrint-WS281x_LED_Status#138]
**Is your feature request related to a problem? Please describe.**
it is a feature request
[x] I have read the Get Help Guide
Add a LED control tab near the control tab inside octopi

**Describe the solution you'd like**

this will allow the user to control the LEDs aside the status of the printer. because octopi can be used for other types of devices and not only 3d printers.
the shape of the tab is shown in these images:
![image](https://user-images.githubusercontent.com/42454228/117460240-8d2a9a00-af61-11eb-8447-73cc584c8412.png)

![image](https://user-images.githubusercontent.com/42454228/117460726-0f1ac300-af62-11eb-8eea-9c3d41db3ae0.png)

**Why should this be implemented?**

The implementation of such control makes your application more general and also there are many other projects out there which are using octopi but they are not 3d printers e.g. many inhouse made devices like dynamic sculptors.

**Comment by cp2004** [comment]
What would be the benefit of manually controlling LEDs in OctoPrint vs. a dedicated project such as [WLED](https://github.com/Aircoookie/WLED)?

**Comment by ShadowOfTheDamn** [comment]
please See this product:
https://sisyphus-industries.com/
maybe someone is going to control his sand table CNC with octopi and the LEDs with the same hardware.

**Comment by cp2004** [comment]
Hi, unfortunately I can't work on 'maybe' someone will use this for something completely different - especially not for something that would require as much work as this.

So no, I can't make a custom tab for control now. If you don't use OctoPi, use something like WLED, which would work just fine for that.

**Comment by ShadowOfTheDamn** [comment]
OK man,
maybe in here means I am using this for my DIY project for a sand table controled by octopi and it has 240 ws2812 LEDs. But seems you are not interested. No Problem. I would hope for you the bests. I will figure some other way for writing my own plugin. Regards
