### ISSUE TITLE
Documentation improvement - API commands

### ISSUE THREAD

**Issue by TDI4** [cp2004/OctoPrint-WS281x_LED_Status#140]
**Is your feature request related to a problem? Please describe.**
I liked to implement my printer in my home automation deeper than Octoprint binding in Openhab, so i started to work on power on/off the PSU with MQTT, switch lights with MQTT and so on. With the "PSU Control" plugin and it's documentation it worked flawlessly, but with this plugin I had to dig much deeper. Your github wiki is pretty fine, but the commands tab (at least for me) did not helped a lot. https://cp2004.gitbook.io/ws281x-led-status/v/0.7.x/documentation/host-commands 

response: { "status" : 400, "response" : Expected valid command "data" : {"command":"WS_LIGHTSON"} }

**Describe the solution you'd like**
Finally I found the solution in your code itself (octoprint_ws281x_led_status/api.py) where you define for example "CMD_LIGHTS_ON = "lights_on" insted of "@WS_LIGHTSON" what's in the documentation. Since I modded it in my "MQTT Subscribe" plugin it works.

response: { "status" : 200, "response" : {"lights_on":true,"torch_on":false} "data" : {"command":"lights_on"} }

**Why should this be implemented?**
To prevent others spending half a day finding where's the problem in the command.

**Additional context**

With this setup it works. Thank you in advance for your effort, and by the way, the plugin is pretty awesome, instead of using Marlin's built-in feature :) 
![2021-05-08_21h01_57](https://user-images.githubusercontent.com/70479047/117550435-a8b8a200-b040-11eb-91a8-46d4aa49318a.png)

**Comment by cp2004** [comment]
This is the page you want:

https://cp2004.gitbook.io/ws281x-led-status/documentation/rest-api

The commands you found, are host @ commands. These can be added to gcode scripts or other plugins that execute gcode commands. They aren't API commands.

**Comment by TDI4** [comment]
I've seen that page, but you mention "see blow" but the API commands are missing, and not equal to the host @ commands. That's why I say it's confusing, and if you add that 5 commands to the documentation, you could save time for someone else who would like to use it.
![2021-05-08_23h19_43](https://user-images.githubusercontent.com/70479047/117553819-ee329a80-b053-11eb-860f-8c631394b8e9.png)

**Comment by cp2004** [comment]
Hmm, below that _used_ to be a table there that documented all the options. I wonder where it went. Will check and fix ASAP - it should have been there, but I wasn't aware it had gone missing. Now to hunt down a missing table on the internet.

**Comment by cp2004** [comment]
https://github.com/cp2004/OctoPrint-WS281x_LED_Status/commit/ab6cd3e94f841f754302cb880fe508b2c89318ca#diff-b321f270a4612b13844ce604e3bbdcf9f3cdfc5dafdef03c2832aafbe07014eeL93-L106

^ See proof! I'm not going mad...

**Comment by cp2004** [comment]
Apologies for the inconvenience there, it is back at https://cp2004.gitbook.io/ws281x-led-status/documentation/rest-api#commands

**Comment by TDI4** [comment]
Thank you for the fast response :) Now it looks (again), how it shoud be. Perfect!
