### ISSUE TITLE
[Request]: Provide Status Info via Host @ Command

### ISSUE THREAD

**Issue by willpuckett** [cp2004/OctoPrint-WS281x_LED_Status#146]
### What would you like implemented?

I access all my printer functions via MQTT. I was adding a status sensor for the WS Lights in Home Assistant via the API this morning... and Wow! What a speed difference! 

Would it be possible to implement a host command such as "@status" that would simply return the same JSON as the API GET request?

Cheers!

### Why should this be implemented?

Not terribly important, but so interfaces feel as responsive as possible.

**Comment by cp2004** [comment]
Host @ commands don't provide a way to 'get' any status. When I receive one of them, there is no way to send back any information, so I don't think you will be able to use them in this way - they are just commands, that say 'do something'. I haven't used MQTT/HA/OctoPrint together, but generally gcode commands (@ commands are OctoPrint-specific gcode) don't get a specific response either, at least not from OctoPrint's API.
