### ISSUE TITLE
[Request]: Orangepi compatibility 

### ISSUE THREAD

**Issue by Dtanguy** [cp2004/OctoPrint-WS281x_LED_Status#151]
### What would you like implemented?

Hello !
Is this plugin compatible with others board like Orangepi (model zero) ?

![image](https://user-images.githubusercontent.com/10078093/125936234-d8537abc-d2f6-47a8-ae73-b02ff609a6ad.png)

It has SPI gpio, but the pin id aren't the same as RPI.

### Why should this be implemented?

Orangepi are a cheapest and small alternative to RPI.

**Comment by cp2004** [comment]
The underlying library only supports the Raspberry Pi. I haven't been able to find a cross-platform WS281x driver (in Python), only ones for the Raspberry Pi.
