### ISSUE TITLE
Possible conflict with ADXL345

### ISSUE THREAD

**Issue by lanman1** [cp2004/OctoPrint-WS281x_LED_Status#153]
### Describe your problem

First of all, thank you for this excellent Octo plugin. I have ordered an ADXL345 to use with Klipper's auto resonance calculation.

https://www.klipper3d.org/Measuring_Resonances.html

Unfortunately this uses the Pi's GPIO 08-11. Iirc, you use GPIO10 because of it's SPI capabilities so I'm guessing it's not as simple as selecting another pin.   I don't think I'll need the ADXL345 often, maybe once or twice per year, so how do you suggest I use this?   Remove your plugin while doing the resonance calculation? Disable Octo while doing the calculations? Switch to WLED for driving the LEDs?

Thank you again.

### Please confirm the following

- [X] I have read the Get Help & Troubleshooting guide

**Comment by cp2004** [comment]
Well you can't use both things on the same pin at the same time! Disabling the plugin (& restarting OctoPrint) would be enough to free up the resources, or even just changing the pin number in the LED settings to a different one - it won't work, but it won't try and use pin 10.

Of course switching to WLED is an option as well, but that's up to you - different features & requires the ESP board and setting up WLED as well.

Hope that helps, apologies for the delayed reply I've been away for a week 🙂

**Comment by cp2004** [comment]
Assuming this question was solved since there has been no reply. If you still have issues please feel free to comment!
