### ISSUE TITLE
[Bug]: Ctrl tab activates torch

### ISSUE THREAD

**Issue by Coopski101** [cp2004/OctoPrint-WS281x_LED_Status#155]
### Description of the bug

When i click on the ctrl tab, it auto turns on torch mode. It toggles the state of the button as well, so i can still turn it off. Clicking away from the ctrl tab does nothing, only clicking into it

### Steps to reproduce

1. Be on any tab with torch off but lights on
2. Move to ctrl tab

### What happened instead?

Torch toggles itself on 

### Plugin version

0.7.2

### OctoPrint version

1.6.1

### (if relevant) OctoPi version

0.18.0

### Log Files & Screenshots

![image](https://user-images.githubusercontent.com/80865420/127789453-dc4117a4-50df-49b0-8a62-4e279beda9db.png)
![image](https://user-images.githubusercontent.com/80865420/127789466-45f6133b-59f2-4c98-9872-d93e9154f204.png)

**Comment by cp2004** [comment]
That's a feature, not a bug :)

Under 'Features', you can disable 'Auto on with webcam' and it should not do this any more.
