### ISSUE TITLE
[Request]: Sectional configuration

### ISSUE THREAD

**Issue by MoadikumMoodock** [cp2004/OctoPrint-WS281x_LED_Status#158]
### What would you like implemented?

I would be wonderful if there is a way to set the print  status via sections by LED number. 

### Why should this be implemented?

This would allow those with LED lighting to not simply have it snake around a strip, but could have the lights change from side to side, or other personal configuration, by selecting begin and end pixel numbers into groups that the print/status indicator color change could then follow.

**Comment by cp2004** [comment]
This is on the way at some point. It's quite a large task to rewrite the structure of the plugin to do this, but I have started some foundations. I don't have as much time as I would like to spend on this plugin, but it definitely won't be happening any time soon. I have a *lot* of things on the todo list 🙂 

Covered by issue #121 already.
