### ISSUE TITLE
[Request]: Add command options

### ISSUE THREAD

**Issue by gortador** [cp2004/OctoPrint-WS281x_LED_Status#160]
### What would you like implemented?

Hello !
Is there a possibility of being able to add the effects via commands?  like
@WS_RAINBOW_CYCLE
@WS_BOUNCE

Even all the effects possible via the plugin 
or explain to me how to add this option 

### Why should this be implemented?

to add color play via commands or macros, this will add a nice functionality to be able to manually control and change the desired effects

**Comment by cp2004** [comment]
It's on the list, see #125. I've started some of the groundwork but I really can't tell you when it will be available - things are *really* busy at the moment and I might not be able to fit in working on before the next release.
