### ISSUE TITLE
Can only control the first LED on the strip

### ISSUE THREAD

**Issue by SearchForSunnyD** [cp2004/OctoPrint-WS281x_LED_Status#161]
### Describe your problem

Ender 3 v2
Raspberry PI 4B w/ Octoprint
WS2812B RGB LED Strip w/ 300 LEDs
I have full control over the one LED, but none of the others are turning on. I have checked that the entire strip has power and there is data continuity throughout the strip. Am confused, pls help.

### Please confirm the following

- [X] I have read the Get Help & Troubleshooting guide

### Log files

[plugin_ws281x_led_status_debug.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/7214288/plugin_ws281x_led_status_debug.log)
[octoprint.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/7214289/octoprint.log)

**Comment by cp2004** [comment]
> ### Log files
> No response

As it said on the issue form, please provide the log files. Follow the Get Help guide, and enable debug logging & upload the logs.

**Comment by SearchForSunnyD** [comment]
Edited with logs
I had taken the strips off since i posted initially. I set it back up exactly as i had it before, but i no longer have LED control

**Comment by SearchForSunnyD** [comment]
[plugin_ws281x_led_status_debug (1).log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/7214327/plugin_ws281x_led_status_debug.1.log)
