### ISSUE TITLE
SPI buffer size increased   Error: The file this check expected does not exist

### ISSUE THREAD

**Issue by doubaz222** [cp2004/OctoPrint-WS281x_LED_Status#164]
### Describe your problem

When using the config wizard, I get the error message: "SPI buffer size increased
 Error: The file this check expected does not exist"

I type in the pi's password but there is no confirm button and when I press the enter key, nothing happens. Has anyone else encountered this issue? I have tried through chrome and safari

### Please confirm the following

- [X] I have read the Get Help & Troubleshooting guide

**Comment by cp2004** [comment]
What OS/OctoPrint install combination are you running? Apologies for the delay in responding here.

Could you share the `octoprint.log` file?
