### ISSUE TITLE
odd numbered LED[Bug]: 

### ISSUE THREAD

**Issue by doubaz222** [cp2004/OctoPrint-WS281x_LED_Status#165]
### Description of the bug

Because I have 19 LEDs, when I use the "heating progress" and I set it to "both ends" I get 1 extra LED that just stays white because (i am guessing that) you can't divide 19/2 evenly so it does not know how to handle the extra LED left over

### Steps to reproduce

use 19 LED's (or I am guessing any number not easily divisible by 2 or 3
set plugin to "heating progress" and then to "both ends"
Fire off a print and the left most LED will remain white 

### What happened instead?

LED remained White

### Plugin version

0.7.2

### OctoPrint version

1.7.0

**Comment by cp2004** [comment]
It's intentional, as you guessed to shorten the number used for that effect to an even number, however it should turn the LED off rather than turning it white. I'll check it out and hopefully fix it.

**Comment by cp2004** [comment]
Fixed, ready for 0.8.0. Hoping to get it out soon but no guarantees of when that might be. There'll be a release candidate beforehand, switch to the 'Release Candidate' channel in the software update section to get notified when it is available.

**Comment by cp2004** [comment]
0.8.0 has been released (finally...!)
