### ISSUE TITLE
WS2801

### ISSUE THREAD

**Issue by wschadow** [cp2004/OctoPrint-WS281x_LED_Status#166]
### What would you like implemented?

Hi,

it's a great project / feature. I run a W2801 with some scripts on the Raspberry. Any chance you support W2801 in your project?

Thanks,
Wolfgang

### Why should this be implemented?

WS2801 support

**Comment by cp2004** [comment]
I can only do it if there's support in the Python library that the plugin uses. That can be found here https://github.com/jgarff/rpi_ws281x

I highly doubt anything extra will be added in that library, since it doesn't see many updates ever.

**Comment by wschadow** [comment]
Thanks! Would it be possible to use this lib instead: https://github.com/adafruit/Adafruit-WS2801-Library
