### ISSUE TITLE
WS281x LED Status

### ISSUE THREAD

**Issue by IanWantage** [cp2004/OctoPrint-WS281x_LED_Status#167]
### Describe your problem

I'm trying to control 12 pixel Adafruit NeoPixel Ring - 5050 RGB LED with Integrated Drivers with WS281x LED Status plugin. I wired the ring to 5V charger, connected ground with Raspberry Pi and data in with GPIO10 as recommended, but the ring does not work. 

When trying to perform OS Config Test in WS281x LED Status plugin test fails to 
-Enable SPI (This test did not pass)
-increase SPI buffer size (Error: The file this check expected does not exist)
-core_freq_min correct in /boot/config.txt  (This test did not pass).

Should I somehow enable SPI? Is it possible via Octopi?

I admit that for more than half of things I'm describing above I don't know how how they work!

### Please confirm the following

- [X] I have read the Get Help & Troubleshooting guide

**Comment by cp2004** [comment]
Could you upload the log files as requested?

> Should I somehow enable SPI? Is it possible via Octopi?

When the tests fail, if it is fixable they give you a button that you can click, providing your password, to fix the problem

**Comment by IanWantage** [comment]
yes, it is fixable (and seems fixed after providing password and pressing button), but light does not work and whenever I run test again - problem persists

**Comment by cp2004** [comment]
> -increase SPI buffer size (Error: The file this check expected does not exist)

This error about the file not existing is slightly misleading - it occurs when SPI is not enabled. You still need to enable SPI and then reboot to use the plugin.
