### ISSUE TITLE
[Bug]: Documentation webside, broken link

### ISSUE THREAD

**Issue by Kyrunix** [cp2004/OctoPrint-WS281x_LED_Status#170]
### Description of the bug

Not a serious bug. But i think nobody noticed it, since.... ever? :D

On the documentation webside (gitbook.io), the link to the plugin listing is broken. Its only a typo.

Current link:
https://plguins.octoprint.org/plugins/ws281x_led_status

Correct link:
https://plugins.octoprint.org/plugins/ws281x_led_status

### Steps to reproduce

1. Open [documentation page](https://cp2004.gitbook.io/ws281x-led-status/)
2. Click on "Plugin Listing" on the top of the page

### What happened instead?

Error 404

### Plugin version

Not necessary

### OctoPrint version

Not necessary

**Comment by cp2004** [comment]
Thanks, have fixed it. It could have been there forever....

I was editing some of the stuff on GitBook this morning, and they broke a lot of things recently that almost make me want to move the docs again...

**Comment by Kyrunix** [comment]
Thanks for such a fast response and fix. Have a nice day. Will try this plugin today and hope it is perfect for my setup :)

Have a nice weekend 👍
