### ISSUE TITLE
Process event dose not start

### ISSUE THREAD

**Issue by HerrHaseGermany** [cp2004/OctoPrint-WS281x_LED_Status#181]
### Describe your problem

After warm up the led stripe stays red. it seems that it switches to the "Sets LEDs to a custom effect until the next event happens." and stays there... i dont know what to do

### Please confirm the following

- [X] I have read the Get Help & Troubleshooting guide

### Log files

[octoprint.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/8034355/octoprint.log)
[plugin_ws281x_led_status_debug.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/8034365/plugin_ws281x_led_status_debug.log)

**Comment by HerrHaseGermany** [comment]
this happend after update to 0.8 before was fine

**Comment by HerrHaseGermany** [comment]
rechecked, after changing "Sets LEDs to a custom effect until the next event happens." it happens the same way, staying red after warmup

**Comment by cp2004** [comment]
Thanks for the bug report. I'm away at the moment but will take a look as soon as I can.

**Comment by biancapascal** [comment]
My leds do show warming up and then they randomly go up and down in white and previously neatly led by led in color to show the percentage.

**Comment by HerrHaseGermany** [comment]
i have observed some prints now, what i can say is, that the process event will start eventualy, but sometimes long after the print has started

**Comment by cp2004** [comment]
Confirmed there is a bug here, needs fixing.

**Comment by cp2004** [comment]
Fixed, will be released as 0.8.1 when I get the other open bug report fixed as well.

**Comment by cp2004** [comment]
0.8.1 has been released.
