### ISSUE TITLE
[Bug]: LEDs are in Heat mode after printing has started

### ISSUE THREAD

**Issue by DeNohvo** [cp2004/OctoPrint-WS281x_LED_Status#183]
### Description of the bug

I will start a print and it will start to heat as normal and LEDs will light Blue to Red, however when the print actually starts the LEDs stay red, until half the first layer has printed then it switches to monitoring the print progress.

I also have it set so it only tracks the bed heating and not the hotend, but that seems to be ignored. This was so that once the bed is heated the LEDS do not reset for hotend heating and LEDs just stay red until printing starts.

Start Bed Heating > LEDs Blue to Red > Start Hotend Heating > LEDs reset and start the Blue to Red sequence again.

### Steps to reproduce

start print
leds start changing from blue to red
print starts and leds are still red
first layer starts
leds are red
halfway in first layer leds changes to print progress 

### What happened instead?

This was not happing on the old version, only started when i upgraded. 

### Plugin version

latest

### OctoPrint version

1.7.3

**Comment by cp2004** [comment]
So are there two issues here?

1. Disabling tracking tool heating is broken
2. After heating, progress bar is not replaced for a while?

Unfortunately I can't look into them without the log file. The `octoprint.log` and `plugin_ws281x_led_status_debug.log` preferably with 'Debug logging' checked on the features tab.

**Comment by cp2004** [comment]
Any news here @JonSnow88?

**Comment by biancapascal** [comment]
The problem with the led's are still not solved. 
The leds are still jumping in a strange way in the color white.
If i load version 0.7 everything works normal, but in previous version and this 0.8 releas its not.
[plugin_ws281x_led_status_debug.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/8304789/plugin_ws281x_led_status_debug.log)
.

**Comment by cp2004** [comment]
@biancapascal that is not related to this issue. If you have a different issue please open your own bug report so the issues do not conflict.

**Comment by cp2004** [comment]
@JonSnow88 I need replies to my questions if I'm going to investigate bug reports please. Nearly a month on from opening the issue.
