### ISSUE TITLE
[Feature Request]: Add `@WS TORCH_TOGGLE` command 

### ISSUE THREAD

**Issue by MattW42** [cp2004/OctoPrint-WS281x_LED_Status#184]
### What would you like implemented?

Please add an `@WS TORCH_TOGGLE` command similar to `@WS LIGHTS_TOGGLE`

### Why should this be implemented?

This would benefit users of Octodash when configuring custom command buttons. Providing an ability to toggle torch mode and lights on/off via the Octodash touch screen.

(As suggested on Discord, thanks)

**Comment by cp2004** [comment]
This will be quick to add and so I'll add it to the list for an 0.8.1 release, along with the fix for #181

**Comment by cp2004** [comment]
Added & released as 0.8.1.
