### ISSUE TITLE
[Feature Request]: Setting to invert color of the torch icon

### ISSUE THREAD

**Issue by trevor229** [cp2004/OctoPrint-WS281x_LED_Status#185]
### What would you like implemented?

I would like to be able to invert the color (from black to white) of the icon that enables the torch mode of the leds. I run a dark theme with UI customizer and it is hard to see the torch icon with black on dark grey.

I tried using the custom CSS feature of UI customizer for this and it worked before, but not anymore.

### Why should this be implemented?

This would help people who use dark themes from octoprint or third party plugins be able to more easily see the icon and match their themes. Also, (I assume) it would be relatively easy to implement.

**Comment by cp2004** [comment]
This is possible to do already with 0.8.0. In the torch icons settings you can edit the colour of it to whatever you want. Definitely a worthwhile feature, but one that's already done!

> Also, (I assume) it would be relatively easy to implement.

Please avoid comments like this unless you are either going to implement it with a PR or a contributor who is familiar with what's *actually* got to be done. To implement this originally, I had to change the icon and edit the icons content manually to allow changing the colour, so it wasn't easy. It's possible maintainers will find it annoying to say this when people are requesting for them to do stuff.
