### ISSUE TITLE
PWM access for WS2812

### ISSUE THREAD

**Issue by freddo99** [cp2004/OctoPrint-WS281x_LED_Status#187]
### Describe your problem

Thank you for a really great project.
I am trying to get access to the Neopixel WS2812, but cannot use GPIO10 due to TFT screen.
I know that it is against advice, but I am hoping to use GPIO13 (PWM) instead.
Could you please tell me how to reveal the PWM option in the LED Strip Editor?

### Please confirm the following

- [X] I have read the Get Help & Troubleshooting guide

**Comment by cp2004** [comment]
All the relevant settings (pins etc) are there except the PWM channel, if you must change it for whatever reason then it must be done in config.yaml using the `strip.channel` setting. You can see the default structure and all the keys here

https://github.com/cp2004/OctoPrint-WS281x_LED_Status/blob/e2d41df4e6bc04ac4b80985a87aa423e996202c5/octoprint_ws281x_led_status/settings.py#L20
