### ISSUE TITLE
ERROR: RuntimeError('ws2811_init failed with code -13 (Unable to initialize SPI)')

### ISSUE THREAD

**Issue by volt64bolt** [cp2004/OctoPrint-WS281x_LED_Status#189]
### Describe your problem

I can't get the lights to turn on, at first I thoughts the lights were dodgy but I checked the logs and found the line `ERROR: RuntimeError('ws2811_init failed with code -13 (Unable to initialize SPI)')` (they might still be dodgy lights but this seems like the main culprit)
this log is without debug logging enabled:
[plugin_ws281x_led_status_debug.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/8491459/plugin_ws281x_led_status_debug.log)
 this is after i enabled debug logging:
[plugin_ws281x_led_status_debug.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/8491466/plugin_ws281x_led_status_debug.log)
[plugin_ws281x_led_status_debug.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/8491472/plugin_ws281x_led_status_debug.log)

I am running a raspberry pi 4b and ws2812 5v leds, powered with a 600ma 4.5v power supply, can change this from 3v to 5v and have tested on each setting, attached below are images of the setup, with the pins unplugged. I did triple check I plugged them into the right slots
![PXL_20220414_172143962](https://user-images.githubusercontent.com/81176807/163455689-2ed2a85d-3466-4221-9adc-b9abc4859195.jpg)
![PXL_20220414_172250355](https://user-images.githubusercontent.com/81176807/163455722-c46bc84b-0086-4e31-899d-b96473d3e591.jpg)
![PXL_20220414_172325554](https://user-images.githubusercontent.com/81176807/163456895-5aa6f77d-05b1-41b7-960b-11dc22a61f24.jpg)
![PXL_20220414_172303997](https://user-images.githubusercontent.com/81176807/163455610-4e642c75-68d6-45d8-932d-8ba2affd2ba1.jpg)
 

### Please confirm the following

- [x] I have read the Get Help & Troubleshooting guide

### Log files

[plugin_ws281x_led_status_debug.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/8491473/plugin_ws281x_led_status_debug.log)
[octoprint.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/8491474/octoprint.log)

**Comment by volt64bolt** [comment]
how do i close this now?

**Comment by cp2004** [comment]
There should usually be a close button at the bottom, but I can do it too.

(Resolved on discord, changed PSU, in case I forget why this is closed now)
