### ISSUE TITLE
[Bug]: Upgrading Marlin to bugfix-2.0.x

### ISSUE THREAD

**Issue by Goldi-2022** [cp2004/OctoPrint-WS281x_LED_Status#192]
### Description of the bug

I have done this update to my printer (CR010 V2).

The progress feature (heating and printing progress) no longer work.

I suspect that I need to change something in Marlin, but I hope that because you know what your software monitors, you would know point me in the right direction.

Thank you for looking.

### What happened instead?

Progress stopped working.

### Plugin version

Version 0.8.1

### OctoPrint version

Version 1.8.1

**Comment by cp2004** [comment]
I have no idea how an upgrade to Marlin would have stopped that working other than if it did not report the temperatures to OctoPrint any longer, which would be evident on the temperature graph or terminal screen. There is also very little information here for me to base any advice on.

**Comment by Goldi-2022** [comment]
Hi,

First of all, thank you for taking the time to reply.

Good point about checking the temperature output in the Octoprint
terminal.  The printer is outputting this data.

Lastly ... I restarted everything, and the plugin is working fine.

Thanks again,
Derek

**Comment by cp2004** [comment]
Well that's good that it's working now 🙂
