### ISSUE TITLE
[Bug]: LED Strip stuck on green light

### ISSUE THREAD

**Issue by juliomtz00** [cp2004/OctoPrint-WS281x_LED_Status#201]
### Description of the bug

Hi, I've been recently workinfg on a project with the WS2812b LED Strip, and everything had been running great but someone used my desk and moved the voltage on my power supply so instead of giving 5V as is needed by my strip, I ended up giving 13V for a couple seconds and ended up frying the chip 74xxxxxx for which I have a spare one, but now my LED Strip is stuck on a single first green LED whenever I connect it to power, and I've already tried connecting the data line individually for a couple of leds and they do turn on, only the first one doesn't which is weird because whatever side I connect it, as soon as I apply voltage the same green LED turns on.

I had been reading that it could be a problem with the data line that got bad because of the increased voltage, but didn't quite get it, could someone tell me if it has happened to someone here and how did they resolve it?

### Steps to reproduce

1. Connect the LED Strip Red cable to voltage and white one to ground and green to the 74xxxxxx for the Raspberry PI Signal.
2. Run any code that turns on the LEDs.

### What happened instead?

Only the first led turns on green and all the other ones don't. I'm guessing they're not getting any signal from the data line.

### Plugin version

-

### OctoPrint version

-

**Comment by cp2004** [comment]
It does sound like the first LED might be fried. Are you able to bypass it and connect your wires up to the second LED in the strip, to test it? If the LEDs further along the chain still work, you can cut out just that first LED and everything else works fine.

**Comment by cp2004** [comment]
@juliomtz00 were you able to test it any more?

**Comment by nnw522** [comment]
Oh no sorry to here that. I have unfortunately made the same mistake with my 3D Printer. The short and simple answer is most likely fried, but also could be the just the first led. Most likely all the LEDs in the string took that higher voltage. I had to replace all mine.

**Comment by cp2004** [comment]
Since there has been no reply to repeated requests for information, I'm closing this issue. If you still need help please do reply.
