### ISSUE TITLE
Separate Neopixel Strips 

### ISSUE THREAD

**Issue by russrams89** [cp2004/OctoPrint-WS281x_LED_Status#219]
### Describe your problem

Hello,

I was just wondering if there was a way to program certain neopixels to display separately? I want to install an LED strip  under my printer for a progress bar and I also have a 16 bit LED ring I wanted to mount somewhere else to show the progress as well. They would both show the same events but I would like for them to fill up separately, is this possible?

Thanks!

### Please confirm the following

- [X] I have read the Get Help & Troubleshooting guide

**Comment by cp2004** [comment]
This is not currently a thing, but I would like to add the ability to control segments of your strips separately in the future - I think there's already an issue open for it. Can't say when that will be a thing, but some of the groundwork was laid in the current version of the plugin - it uses the idea of segments already behind the scenes. So it's on the way but might not be available for users for a while.
