### ISSUE TITLE
[Bug] Power calculator text box not visible in discoranged in Themeify

### ISSUE THREAD

**Issue by HenryDeng1** [cp2004/OctoPrint-WS281x_LED_Status#23]
Power calculator text box not visible in discoranged in Themeify

1. Go to octoprint settings
2. Click on WS281x_LED_status_ plugin
3. Click on Utilities 

**What did you expect to happen**

**Logs and screenshots**
[plugin_ws281x_led_status_debug.log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/5103320/plugin_ws281x_led_status_debug.log)

[octoprint(1).log](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/files/5103326/octoprint.1.log)
![image](https://user-images.githubusercontent.com/69972821/90775749-8b219c00-e33c-11ea-9280-01515307fc36.png)

**Version of plugin and OctoPrint**

V 0. 5. 0 Plugin
Themeify: v 1.2.2
Octoprint: v 1.4.2
**(If applicable) Browser version & browser error console**

**Additional context**

**Comment by cp2004** [comment]
Going to get 0.5.1 out maybe today, definitely by tomorrow.
