### ISSUE TITLE
Getting random noise in the strip

### ISSUE THREAD

**Issue by stevenpaulr** [cp2004/OctoPrint-WS281x_LED_Status#25]
**What's your question?**

I have a 2812b strip, I got it to light up, but it keeps giving just random data to the LEDs. I've linked a video. This happens if it's printing or not.
[https://drive.google.com/file/d/1z_jEEHWWtezigX6MbDfpdDTJl2UEoM-g/view?usp=sharing](https://drive.google.com/file/d/1z_jEEHWWtezigX6MbDfpdDTJl2UEoM-g/view?usp=sharing)

**Comment by cp2004** [comment]
Make sure you have a common ground between the power supply and the Pi - see in the image below, there is a ground connection going to both the Pi and power supply.
![image](https://user-images.githubusercontent.com/31997505/91228201-c26ac100-e71f-11ea-88ce-cd33e5b898cb.png)

**Comment by stevenpaulr** [comment]
That did it. Thanks!

**Comment by cp2004** [comment]
Enjoy the plugin!

**Comment by dtdor** [comment]
Having a crazy flickering/flashing problem when I choose anything except solid white. Grounds are common already so I'm a little stumped. I don't have a diode in place yet, haven't ever needed one before. I plan to try that and a 470 ohm resistor in the data line. Any suggestions would be great.
