### ISSUE TITLE
Change LED Direction

### ISSUE THREAD

**Issue by wkoetz** [cp2004/OctoPrint-WS281x_LED_Status#37]
Is it possible to change the LED direction?

**Comment by cp2004** [comment]
Not currently. @11chrisadams11 was working on that in #14 , and I had plans to turn it into a global setting, reverse direction.

**Comment by cp2004** [comment]
From 0.6.0 it will be possible to reverse the order of progress effects. @wkoetz is that what you wanted? I don't have plans to convert any other effects before the next release.

**Comment by wkoetz** [comment]
Great and yes, this is exactly my wish! THX and take care, stay healthyWilfriedVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Charlie Powell <notifications@github.com> Datum: 25.10.20  16:04  (GMT+01:00) An: cp2004/OctoPrint-WS281x_LED_Status <OctoPrint-WS281x_LED_Status@noreply.github.com> Cc: wkoetz <wkoetz@keng.de>, Mention <mention@noreply.github.com> Betreff: Re: [cp2004/OctoPrint-WS281x_LED_Status] Change LED Direction (#37) 
From 0.6.0 it will be possible to reverse the order of progress effects. @wkoetz is that what you wanted? I don't have plans to convert any other effects before the next release.

**Comment by cp2004** [comment]
Hey @wkoetz  - could you test 0.6.0-rc.1 with this feature in it?

Can be installed by using the following URL in plugin manager > Get more > ...from URL:
```
https://github.com/cp2004/OctoPrint-WS281x_LED_Status/archive/0.6.0-rc.1.zip
```

Please provide general feedback in the [feedback ticket](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/issues/49) - an 'all is working fine' is valuable feedback since it lets me know people are testing this release. Thanks!

**Comment by wkoetz** [comment]
Yes, now it works great for the progress bar. My first thinking was it doesn't work, because it has no effect to "Color Wipe" at startup effect. Maybe you can add a reverse Color Wipe as well?
Nevertheless great work and I am happy with that!

**Comment by cp2004** [comment]
Maybe it will be for all effects in the future, I will think about it for future releases.

**Comment by cp2004** [comment]
0.6.0 has been released.
