### ISSUE TITLE
[Feedback] 0.6.0 Feedback ticket

### ISSUE THREAD

**Issue by cp2004** [cp2004/OctoPrint-WS281x_LED_Status#52]
Ticket for you to provide *general* feedback on the release. Maybe you like a particular feature, or have a quick question about something new in this release. Or anything else!

For feature requests and bug reports, please [open a new issue](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/issues/new/choose) using the templates.

Thank you for using this plugin. If you have enjoyed using this, please consider [supporting it's development!](https://github.com/sponsors/cp2004)

**Comment by cr0wm4n** [comment]
ahh 0.60 already released, im upgrading to that now

**Comment by Prutsium** [comment]
Installed 0.6.0 on a Zero and "Yes" it works.
Thanks for the quick fixing.

**Comment by cr0wm4n** [comment]
yes the temp thing works fine 👍

**Comment by cp2004** [comment]
Thank you both for the feedback 🙂

**Comment by cr0wm4n** [comment]
thankyou for completing this request :))

**Comment by Drew3164** [comment]
Not working? Did the update and the whole plugin disappear tried reinstalling the plugin and does not appear in the setting/ plugins?

**Comment by cp2004** [comment]
@Drew3164 Please open a full bug report, I suspect the answer lies in the logs.

**Comment by cp2004** [comment]
@Drew3164 - just checking in, guess this is no longer an issue?

**Comment by Drew3164** [comment]
No I fix it by reinstalling a new octoprint and your new update help out
alot.



Thanks for your help and getting back to me..


Keep up the good work.
