### ISSUE TITLE
[Feature Request] Enhancement to progress effect for printers with LED strip on Z (sides) and X (top) of printer

### ISSUE THREAD

**Issue by james-fry** [cp2004/OctoPrint-WS281x_LED_Status#57]
Thanks for the plugin - its working great! love it

I have an i3 style printer with a frame surrounding the print bed.
I have installed a strip of ws2812 leds around three sides of that frame - up one side of the frame, across the top of the frame, and back down the other side.
This means the progress effect tracks up then across then back down around the frame - which limits the ability to check the approx progress at a glance.

It would be great if its possible for the print progress effect to be enhanced toincrement from both ends of the strip so that the progress "bar chart" is on both sides of my printer with 0% at the bottom and 100% at the top.

Even better would be to be able to define segments for sides and top of printer and use these in different ways.
e.g. solid white light from top LEDs to illuminate the print bed, and progress tracked up both sides.

Id have a crack at writing it myself by my python is practically nonexistent!

**Comment by james-fry** [comment]
Current behaviour:
![image](https://user-images.githubusercontent.com/5823294/99701286-29ccae80-2a8c-11eb-96e1-144face5bcb0.png)

**Comment by james-fry** [comment]
Proposed enhancement:
![image](https://user-images.githubusercontent.com/5823294/99701330-39e48e00-2a8c-11eb-8c3d-cd1616e64be0.png)

**Comment by cp2004** [comment]
Its on my list to create different progress effects that may look better on your machine (for example, build from both ends).

I don't currently have any plans to implement customisable segments whilst I am aware that people would *like* that, it is quite a big project to implement. So I can say yes to some improvements, but not quite different zones *just yet*. Maybe in the further future as this project develops.

**Comment by cp2004** [comment]
I have implemented a progress effect that runs 'from both ends', ready for 0.7.0 - expect a release candidate some point in the next week.
