### ISSUE TITLE
[Bug] Cooling progress effect

### ISSUE THREAD

**Issue by Bimb0** [cp2004/OctoPrint-WS281x_LED_Status#58]
The cooling progress effect only monitors the instrument temperature, even if I have it set to monitor the bed. Monitoring ends when the tool temperature is reached.

OctoPrint 1.4.2
OctoPI 0.18
Python 3.7.3

**Comment by cp2004** [comment]
Can confirm, this does not appear to work.

**Comment by cp2004** [comment]
Fixed for 0.7.0, it was simply a UI error where there was a typo in the setting.

**Comment by cp2004** [comment]
Hey @Bimb0, 0.7.0rc1 is [out now for testing](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/releases/tag/0.7.0rc1) - there's a [feedback ticket here](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/issues/119) for any comments on the release. Any feedback is appreciated.

**Comment by cp2004** [comment]
0.7.0 has been released.
