### ISSUE TITLE
[Feature Request] A way to add ON/OFF to the octoremote Android

### ISSUE THREAD

**Issue by salilgupta4** [cp2004/OctoPrint-WS281x_LED_Status#6]
Is there a way to add the button to the Octoremote so that the Lights can be switched ON or OFF from the app itself. Even though the timed option is there. But sometimes just doesnt help. 

Thanks,

**Comment by cp2004** [comment]
@salilgupta4 Can you tag the OctoRemote developer here? The lights on/off can be accessed from the API but as far as I know there isn't a way to add custom API commands there.

**Comment by cp2004** [comment]
Not sure if the app is open source, but you may be able to add a custom control. I can take a look at some point, but would need to work out how they work first.

**Comment by salilgupta4** [comment]
The developer is Octoremote itself. 
![image](https://user-images.githubusercontent.com/31687874/89126760-e878b900-d505-11ea-9271-c7cbde5494af.png)
So here in the description they have mentioned that we can add some controls. Just like you said, the function has to be called, but how?
![image](https://user-images.githubusercontent.com/31687874/89126775-080fe180-d506-11ea-97a9-3a5fcea0ff69.png)

This is no major issue. But can spread its wings to android too. And actually the Octoremote app is pretty handy.

Thanks for looking into it.

**Comment by cp2004** [comment]
@salilgupta4 Solution for you! 
In 0.4.0 I have added 2 @ commands, `@WS_LIGHTSON` and `@WS_LIGHTSOFF`

These can be sent in the gcode stream to OctoPrint, picked up and interpreted.

To get them into OctoRemote, head to Settings > Controls >Edit custom controls. Then add command, in the `commands` box you can put either of the above. Once saved, they are on the control tab in OctoRemote

**Comment by salilgupta4** [comment]
Thats a big help. Thanks so much. 

No many people provide solutions that quickly.

**Comment by cp2004** [comment]
The @ commands were on my list already, but got bumped forwards when I noticed it would solve this... Glad to know it helped!

**Comment by gortador** [comment]
Is there a possibility of being able to add the effects via commands? Gcode ? or @WS_RAINBOW_CYCLE ? or other ?

**Comment by 7R0J4Ner** [comment]
@cp2004 would it be Possible to add something like `@WS_LIGHTSTOGGLE` ?
I dont like to have 2 Buttons to Controll my Lights.
