### ISSUE TITLE
[Feature Request] Single LED for printing progress

### ISSUE THREAD

**Issue by Jester4977** [cp2004/OctoPrint-WS281x_LED_Status#70]
It would be great if you could set a single LED to be lit with the selected color instead of the entire left side of the bar.  For example, if your print is halfway completed, just light up the LED in the center of the bar green, and the rest of the LEDs can remain white.  Using the majority of the LEDs white helps with timelapse videos, and having a single LED moving from left to right can provide the progress without disrupting the color for the pictures/video.

**Comment by cp2004** [comment]
Similarly to #57 and #59, I'll be adding a wide range of progress style effects in 0.7.0. When this will be, who knows, but at some point it will arrive.

**Comment by cp2004** [comment]
Implemented via the above commits, ready for 0.7.0.

**Comment by cp2004** [comment]
Hey @Jester4977, 0.7.0rc1 is [out now for testing](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/releases/tag/0.7.0rc1) - there's a [feedback ticket here](https://github.com/cp2004/OctoPrint-WS281x_LED_Status/issues/119) for any comments on the release. Any feedback is appreciated.
