### ISSUE TITLE
[Feature Request] Option to auto-activate torch mode when viewing webcam stream

### ISSUE THREAD

**Issue by cp2004** [cp2004/OctoPrint-WS281x_LED_Status#74]

**Comment by scr34m88** [comment]
Another Feature request regarding to the webcam stream.
Enable the torch for timelaps wait until the webcam has taken a picture and disable torch

**Comment by cp2004** [comment]
I can't reliably work out when the built in timelapse is going to fire, if you install and use OctoLapse you can do this using it's scripts. See here: https://github.com/cp2004/OctoPrint-WS281x_LED_Status/wiki/Tips-and-Tricks#timelapse-flash

**Comment by cp2004** [comment]
Implemented via the above commit, ready for 0.7.0.
