### ISSUE TITLE
Ws2812 Turns only white

### ISSUE THREAD

**Issue by DBZwerg** [cp2004/OctoPrint-WS281x_LED_Status#79]
**What's your question?**
I‘ve Setup your Plugin With my ws2812 Strip, Bit can‘t control them.
They only Lights white in Full Power.
I use a levelshifter „ TXS0108E“.

**Comment by cp2004** [comment]
Check the solution in #75 first, and upload the log files - `octoprint.log` and `plugin_ws281x_led_status_debug.log` please.

**Comment by DBZwerg** [comment]
Thanks dir your fast reply!

After I bypassed the levelshiftee it worked:-)
